version: '3'
services:
  flask-db-app:
    depends_on: 
      - 'mysql'
    container_name: flask-db-app
    build:
      context: authors/
      dockerfile: Dockerfile
    image: flask-db-app:latest
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=root
      - AUTH_SECRET_KEY=secret
    expose: 
      - 5000
    restart: always
    networks:
      - internal

  flask-auth-app:
    depends_on:
      - 'mysql'
    container_name: flask-auth-app
    build:
      context: auth/
      dockerfile: Dockerfile
    image: flask-auth-app:latest
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=root
      - AUTH_SECRET_KEY=secret
    expose:
      - 5000
    restart: always
    networks:
      - internal

  mysql:
    container_name: mysql
    image: mysql:8.0
    healthcheck:
      test: [ "CMD", "/usr/bin/mysql", "--host=127.0.0.1", "--user=root", "--password=root", "--execute", "SELECT 1;" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=author
    networks: 
      - internal

  nginx:
    container_name: nginx-lb
    build:
      context: nginx/
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    image: nginx-lb:latest
    ports: 
      - 80:80
    restart: always
    networks:
      - internal 

networks:
    internal:
      driver: bridge
